modLoader="javafml"
loaderVersion="[34,)"
license="LGPL-3.0"
[[mods]]
modId="janoeo_arsenal"
version="${file.jarVersion}"
displayName="Janoeo - Arsenal"
authors="AlasDiablo, lIotaMiu, Egame257 and Safyrus"
description='''
Janoeo - Arsenal by AlasDiablo, lIotaMiu, Egame257 and Safyrus
'''
[[dependencies.janoeo_arsenal]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.janoeo_arsenal]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.janoeo_arsenal]]
    modId="diolib"
    mandatory=true
    versionRange="[1.0.4,)"
    ordering="AFTER"
    side="BOTH"
